### ISSUE TITLE
Error opening archive: Unrecognized archive format

### ISSUE THREAD

**Issue by jclarke-1** [weave-lab/flanders#7]
I followed the steps in the readme, installing vbox (latest), installing vagrant(latest) and nodejs (latest).

When i run `vagrant up / vagrant up flanders` inside `flanders` I get the error below.

`The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any): `
    `bsdtar: Error opening archive: Unrecognized archive format`

**Comment by clintberry** [comment]
I haven't tested with the latest version of vagrant. I will do it right now.

**Comment by jclarke-1** [comment]
Still breaks for me.
could it be an issue with the version of virtualbox ?

`Bringing machine 'flanders' up with 'virtualbox' provider...`
`==> flanders: Box 'inflection/ubuntu-1404-salt' could not be found. Attempting to find and install...`
    ` flanders: Box Provider: virtualbox`
    `flanders: Box Version: >= 0`

`==> flanders: Loading metadata for box 'inflection/ubuntu-1404-salt'`
    `flanders: URL: https://atlas.hashicorp.com/inflection/ubuntu-1404-salt`

`==> flanders: Adding box 'inflection/ubuntu-1404-salt' (v0.1.0) for provider: virtualbox`
   ` flanders: Downloading: https://atlas.hashicorp.com/inflection/boxes/ubuntu-1404-salt/versions/0.1.0/providers/virtualbox.box`

   `The box failed to unpackage properly. Please verify that the box
    file you're trying to add is not corrupted and try again. The
    output from attempting to unpackage (if any):`

    bsdtar: Error opening archive: Unrecognized archive format

**Comment by clintberry** [comment]
I will remove that box from my vagrant setup and start over...

**Comment by clintberry** [comment]
Looks like that box didn't exist anymore but was saved on my system so I had no idea. I am switching it out for a new one. Once tested, will push to this branch.
